spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sport?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379

  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    test-connection: true
    username: sofacoder@163.com
    password: LDHVTIIOIOILVFCB

